/**
 * Barcha UI matnlari — o'zbek tilida (lotin alifbosi).
 * Kelajakda i18n uchun tayyor.
 */

export const uz = {
  // Umumiy
  common: {
    loading: "Yuklanmoqda...",
    error: "Xatolik yuz berdi",
    success: "Muvaffaqiyatli",
    save: "Saqlash",
    cancel: "Bekor qilish",
    delete: "O'chirish",
    edit: "Tahrirlash",
    add: "Qo'shish",
    back: "Orqaga",
    next: "Keyingi",
    submit: "Yuborish",
    confirm: "Tasdiqlash",
    reject: "Rad etish",
    search: "Qidirish",
    filter: "Filtrlash",
    all: "Barchasi",
    yes: "Ha",
    no: "Yo'q",
    close: "Yopish",
    open: "Ochish",
    required: "Majburiy maydon",
    optional: "Ixtiyoriy",
    actions: "Amallar",
    details: "Batafsil",
    status: "Holat",
    date: "Sana",
    time: "Vaqt",
    name: "Ism",
    description: "Tavsif",
    noData: "Ma'lumot topilmadi",
  },

  // Navigatsiya
  nav: {
    home: "Bosh sahifa",
    dashboard: "Bosh sahifa",
    profile: "Profil",
    settings: "Sozlamalar",
    logout: "Chiqish",
    notifications: "Bildirishnomalar",
    mainMenu: "Asosiy menyu",
  },

  // Auth
  auth: {
    login: "Tizimga kirish",
    register: "Ro'yxatdan o'tish",
    logout: "Chiqish",
    phone: "Telefon raqam",
    phonePlaceholder: "+998901234567",
    password: "Parol",
    passwordPlaceholder: "Kamida 8 ta belgi",
    rememberMe: "Meni eslab qol",
    forgotPassword: "Parolni unutdingizmi?",
    noAccount: "Hisobingiz yo'qmi?",
    haveAccount: "Hisobingiz bormi?",
    firstName: "Ism",
    lastName: "Familiya",
    school: "Maktab",
    schoolPlaceholder: "Maktabni tanlang",
    class: "Sinf",
    classPlaceholder: "Sinfni tanlang",
    role: "Rol",
    loginSuccess: "Tizimga muvaffaqiyatli kirdingiz",
    registerSuccess: "Ro'yxatdan o'tdingiz. Tasdiqlash kutilmoqda.",
    loginError: "Telefon raqam yoki parol noto'g'ri",
    phoneRequired: "Telefon raqam kiritilishi shart",
    phoneInvalid: "Telefon raqam noto'g'ri formatda (+998XXXXXXXXX)",
    passwordRequired: "Parol kiritilishi shart",
    passwordMinLength: "Parol kamida 8 ta belgidan iborat bo'lishi kerak",
    firstNameRequired: "Ism kiritilishi shart",
    lastNameRequired: "Familiya kiritilishi shart",
    schoolRequired: "Maktabni tanlash shart",
    classRequired: "Sinfni tanlash shart",
  },

  // Kutilish sahifasi
  pending: {
    title: "Arizangiz ko'rib chiqilmoqda",
    description:
      "Sizning ro'yxatdan o'tish arizangiz o'qituvchi yoki direktor tomonidan tasdiqlanishi kutilmoqda. Iltimos, kuting.",
    contact: "Muammolar bo'lsa, o'qituvchingizga murojaat qiling.",
    rejected: "Arizangiz rad etildi",
    rejectedReason: "Sabab",
    reapply: "Qayta ariza berish",
    checkStatus: "Holati tekshirish",
  },

  // O'quvchi dashboard
  student: {
    dashboard: "Mening darslarim",
    subjects: "Fanlar",
    lectures: "Ma'ruzalar",
    tests: "Testlar",
    games: "O'yinlar",
    assignments: "Vazifalar",
    books: "Kitoblar",
    leaderboard: "Reyting",
    progress: "Mening taraqqiyotim",
    myResults: "Mening natijalarim",
    startTest: "Testni boshlash",
    continueTest: "Testni davom ettirish",
    submitTest: "Testni yuborish",
    nextQuestion: "Keyingi savol",
    prevQuestion: "Oldingi savol",
    timeLeft: "Qolgan vaqt",
    score: "Ball",
    correct: "To'g'ri",
    incorrect: "Noto'g'ri",
    attempts: "Urinishlar",
    result: "Natija",
    readAloud: "Ovozli o'qish",
    stopReading: "To'xtatish",
    bookmark: "Xatchet",
    bookmarked: "Xatchet qo'yildi",
    entryTest: "Kirish testi",
    entryTestDescription: "Ushbu fan bo'yicha bilim darajangizni aniqlash uchun",
  },

  // O'qituvchi
  teacher: {
    dashboard: "O'qituvchi bosh sahifasi",
    myStudents: "Mening o'quvchilarim",
    pendingStudents: "Kutilayotgan o'quvchilar",
    myLectures: "Mening ma'ruzalarim",
    myTests: "Mening testlarim",
    myGames: "Mening o'yinlarim",
    myAssignments: "Mening vazifalarim",
    analytics: "Analitika",
    addLecture: "Ma'ruza qo'shish",
    addTest: "Test tuzish",
    addGame: "O'yin yaratish",
    addAssignment: "Vazifa berish",
    approveStudent: "O'quvchini tasdiqlash",
    rejectStudent: "Rad etish",
    rejectReason: "Rad etish sababi",
    rejectReasonRequired: "Rad etish sababini kiriting",
    studentApproved: "O'quvchi tasdiqlandi",
    studentRejected: "O'quvchi rad etildi",
    gradeAssignment: "Baholash",
    grade: "Baho",
    comment: "Izoh",
  },

  // Direktor
  director: {
    dashboard: "Direktor bosh sahifasi",
    teachers: "O'qituvchilar",
    classes: "Sinflar",
    students: "Barcha o'quvchilar",
    subjects: "Fanlar",
    lectures: "Maktab ma'ruzalari",
    analytics: "Maktab analitikasi",
    addTeacher: "O'qituvchi qo'shish",
    addClass: "Sinf qo'shish",
    schoolInfo: "Maktab ma'lumotlari",
  },

  // Super admin
  admin: {
    dashboard: "Admin bosh sahifasi",
    schools: "Maktablar",
    directors: "Direktorlar",
    subjects: "Global fanlar",
    users: "Barcha foydalanuvchilar",
    analytics: "Tizim analitikasi",
    addSchool: "Maktab qo'shish",
    addDirector: "Direktor qo'shish",
    addSubject: "Fan qo'shish",
  },

  // Ma'ruzalar
  lectures: {
    title: "Ma'ruzalar",
    add: "Ma'ruza qo'shish",
    pdf: "PDF fayl",
    video: "Video dars",
    audio: "Audio dars",
    ppt: "Taqdimot (PPT)",
    subject: "Fan",
    class: "Sinf",
    uploadFile: "Fayl yuklash",
    subtitles: "Subtitrlar",
    subtitlesRequired: "Video uchun subtitr majburiy",
    addSubtitles: "Subtitr qo'shish",
    generateSubtitles: "AI orqali subtitr yaratish",
    viewLecture: "Ko'rish",
    downloadPdf: "PDF yuklash",
  },

  // Testlar
  tests: {
    title: "Testlar",
    add: "Test tuzish",
    singleChoice: "Bir javobli test",
    multipleChoice: "Ko'p javobli test",
    trueFalse: "To'g'ri/Noto'g'ri",
    fillBlank: "Bo'sh joyni to'ldirish",
    timeLimit: "Vaqt chegarasi (daqiqa)",
    noTimeLimit: "Vaqt chegarasiz",
    maxAttempts: "Urinishlar soni",
    unlimited: "Cheksiz",
    testType: "Test turi",
    entryTest: "Kirish testi",
    postTopic: "Mavzudan keyingi",
    homeStudy: "Uy testi",
    question: "Savol",
    addQuestion: "Savol qo'shish",
    option: "Variant",
    addOption: "Variant qo'shish",
    correctAnswer: "To'g'ri javob",
    points: "Ball",
    image: "Rasm",
    altText: "Rasm tavsifi (alt text)",
    altTextRequired: "Screen reader uchun rasm tavsifi majburiy",
  },

  // O'yinlar
  games: {
    title: "O'yinlar",
    add: "O'yin yaratish",
    wordMatch: "So'z–Ma'no",
    ordering: "To'g'ri tartib",
    memory: "Xotira kartalari",
    wordMatchDesc: "So'zni to'g'ri ma'nosiga bog'lang",
    orderingDesc: "Elementlarni to'g'ri tartibga joylashtiring",
    memoryDesc: "Juft kartalarni toping",
    start: "O'yinni boshlash",
    finish: "Tugalladi",
    timeSpent: "Sarflangan vaqt",
  },

  // Kitoblar
  books: {
    title: "Kitoblar",
    add: "Kitob qo'shish",
    uploadPdf: "PDF yuklash",
    uploadAudio: "Audio yuklash",
    generateAudio: "AI orqali audio yaratish",
    audioSource: "Audio manbai",
    uploaded: "Yuklangan audio",
    webSpeech: "Brauzer (Web Speech API)",
    googleTts: "Platforma (Google Cloud TTS)",
    generating: "Audio yaratilmoqda...",
    generatingWarning: "Bu jarayon bir necha daqiqa davom etishi mumkin",
    manyPagesWarning:
      "Kitob 50 dan ortiq sahifadan iborat. Audio yaratish ko'p vaqt va resurs talab qiladi. Davom etasizmi?",
    preview: "Tekshirib ko'rish",
    listenBook: "Kitobni tinglash",
    readBook: "Kitobni o'qish",
    page: "Sahifa",
    audioPlayer: "Audio pleyer",
    speed: "Tezlik",
    pause: "To'xtatish",
    resume: "Davom ettirish",
  },

  // Leaderboard
  leaderboard: {
    title: "Reyting",
    allTime: "Barcha vaqt",
    weekly: "Haftalik",
    rank: "O'rin",
    student: "O'quvchi",
    score: "Ball",
    change: "O'zgarish",
    myRank: "Mening o'rnim",
  },

  // Bildirishnomalar
  notifications: {
    title: "Bildirishnomalar",
    markAllRead: "Hammasini o'qilgan deb belgilash",
    noNotifications: "Bildirishnomalar yo'q",
    approved: "Arizangiz tasdiqlandi",
    rejected: "Arizangiz rad etildi",
    newLecture: "Yangi ma'ruza qo'shildi",
    newAssignment: "Yangi vazifa berildi",
    assignmentGraded: "Vazifangiz baholandi",
    leaderboardUp: "Reytingda ko'tarildingiz",
    leaderboardDown: "Reytingda tushdingiz",
  },

  // Accessibility
  a11y: {
    skipToContent: "Asosiy kontentga o'tish",
    skipToNav: "Navigatsiyaga o'tish",
    mainMenu: "Asosiy menyu",
    closeMenu: "Menyuni yopish",
    openMenu: "Menyuni ochish",
    loading: "Yuklanmoqda, iltimos kuting",
    pageLoaded: "Sahifa yuklandi",
    screeningTitle: "Sensor tekshiruvi",
    screeningIntro:
      "Bu tekshiruv sizga qulay interfeys rejimini taklif qilish uchun mo'ljallangan. Ixtiyoriy.",
    visionTest: "Ko'rish testi",
    hearingTest: "Eshitish testi",
    motorTest: "Motorika testi",
    skipScreening: "Tekshiruvni o'tkazib yuborish",
    startScreening: "Tekshiruvni boshlash",
    nextStep: "Keyingi bosqich",
    testComplete: "Test tugadi",
    visionMode: "Ko'rish rejimi",
    hearingMode: "Eshitish rejimi",
    motorMode: "Motorika rejimi",
    fontSizeSmall: "Kichik (14px)",
    fontSizeMedium: "O'rta (16px)",
    fontSizeLarge: "Katta (20px)",
    fontSizeXLarge: "Juda katta (24px)",
    contrastNormal: "Oddiy",
    contrastHigh: "Yuqori kontrast",
    contrastDark: "Qorong'i rejim",
    colorBlindNormal: "Oddiy",
    colorBlindProtanopia: "Protanopiya",
    colorBlindDeuteranopia: "Deuteranopiya",
    colorBlindTritanopia: "Tritanopiya",
    reduceMotion: "Animatsiyalarni kamaytirish",
    ttsSource: "Ovoz manbai",
    ttsWeb: "Brauzer (bepul)",
    ttsPlatform: "Platforma (sifatliroq)",
    ttsOwnReader: "O'zimning screen reader dasturim bor",
    subtitlesAlways: "Subtitrlarni har doim ko'rsat",
    accessibilitySettings: "Imkoniyatlar sozlamalari",
    applySettings: "Sozlamalarni qo'llash",
  },

  // Xatolar
  errors: {
    notFound: "Sahifa topilmadi",
    serverError: "Server xatosi",
    unauthorized: "Ruxsat yo'q",
    forbidden: "Kirish taqiqlangan",
    networkError: "Internet ulanishi yo'q",
    fileTooBig: "Fayl hajmi juda katta",
    invalidFileType: "Fayl turi qo'llab-quvvatlanmaydi",
    uploadError: "Fayl yuklashda xatolik",
    tryAgain: "Qayta urinib ko'ring",
  },

  // Maktab/Sinf
  school: {
    name: "Maktab nomi",
    address: "Manzil",
    grade: "Sinf raqami",
    letter: "Sinf harfi",
    className: "Sinf",
    subject: "Fan",
  },

  // Foydalanuvchi profili
  profile: {
    title: "Profil",
    personalInfo: "Shaxsiy ma'lumotlar",
    changePassword: "Parolni o'zgartirish",
    oldPassword: "Eski parol",
    newPassword: "Yangi parol",
    confirmPassword: "Parolni tasdiqlash",
    passwordMismatch: "Parollar mos kelmaydi",
    passwordChanged: "Parol muvaffaqiyatli o'zgartirildi",
    accessibility: "Imkoniyatlar sozlamalari",
    notifications: "Bildirishnomalar",
    saved: "Profil saqlandi",
  },
} as const;

export type UzStrings = typeof uz;
